Repository GlueOps/provisioner, pull requests merged in 2024-12, with the labels that each got.

#8 major: remove tailscale
  Dockerfile
  devbox.json
Labels: Review effort [1-5]: 1

#11 fix: tags
  app/main.py
  app/util/b64.py
  app/util/virsh.py
  app/util/virt.py
Labels: Review effort [1-5]: 2

#12 fix: change encoder to b64
  app/main.py
  app/util/virsh.py
Labels: Review effort [1-5]: 2

#16 fix: ssh key agent issue on startup
  devbox.json
Labels: Review effort [1-5]: 2

#17 feat: add server libvirt install script for debian servers
  install-server.sh
Labels: Review effort [1-5]: 3

#20 fix: add ssh ports to install script
  install-server.sh
Labels: Review effort [1-5]: 2

#22 fix: change installscript from nix pkgs to debian apt pkgs
  install-server.sh
Labels: Review effort [1-5]: 2

#23 fix: downgrade libvirt to match provisioner node
  devbox.json
Labels: Review effort [1-5]: 1
