Repository GlueOps/provisioner, pull requests merged in 2025-05, with the labels that each got.

#65 fix: remove unused install script that was moved to ansible
  install-server.sh
Labels: Review effort 1/5

#66 feat: Add PRCHECKLIST using Pull Request Checklist Buddy
  .github/configs/labeler.yml
  PRCHECKLIST
Labels: enhancement, Review effort 1/5, include-in-release-notes, minor, patch

#67 fix: remove page count to default to 30 images
  app/util/github.py
Labels: Review effort 1/5, include-in-release-notes, patch
