Repository GlueOps/provisioner, pull requests merged in 2025-07, with the labels that each got.

#77 feat: removing unused env variable: PROVISIONER_ENVIRONMENT
  app/main.py
Labels: Review effort 1/5

#78 feat: adding back PROVISIONER_ENVIRONMENT env var
  app/main.py
Labels: enhancement, Review effort 1/5, include-in-release-notes, minor

#80 fix: add command to change tags on import vm
  app/main.py
  app/schemas/schemas.py
Labels: Review effort 2/5, include-in-release-notes, patch, Possible security concern
