Repository GlueOps/provisioner, pull requests merged in 2025-01, with the labels that each got.

#24 major: refactor
  Dockerfile
  app/main.py
  app/schemas/schemas.py
  app/util/regions.py
  app/util/virsh.py
  devbox.json
  devbox.lock
  install-server.sh
Labels: Review effort [1-5]: 4

#19 docs: initial version of docs
  README.md
Labels: Review effort [1-5]: 2

#28 Feat/adding image cache
  Pipfile
  Pipfile.lock
  app/main.py
  app/schemas/schemas.py
  install-server.sh
Labels: Review effort [1-5]: 3

#30 feat: make /v1/list endpoint async to speed it up
  app/main.py
Labels: Review effort [1-5]: 2

#31 fix: background scheduler to only execute cache of images when there …
  Pipfile
  Pipfile.lock
  app/main.py
  app/util/github.py
Labels: Review effort [1-5]: 2

#32 feat: adding timezone change to UTC
  install-server.sh
Labels: Review effort [1-5]: 1

#33 feat: disable password authentication in ssh config
  install-server.sh
Labels: Review effort [1-5]: 1
